config/routes.rb
Timeline::Application.routes.draw do
  resources :timeline_objects

  devise_for :users
  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
  end

  resources :events, :only => [:create, :new,:edit, :show, :update, :destroy]
  get 'timelines', to: 'timeline_objects#index', as: :timelines
  get 'newtimeline', to: 'timeline_objects#new', as: :newtimeline
  get "home/index"
  root :to => 'home#index'

   

end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :timeline_object
	
  	attr_accessible :date, :description, :time, :title, :image, 
  	:image_width, :image_height, :timeline_object_id
	has_attached_file :image, :styles => { :large => "500x500>", :medium => "400x400#", :thumb => "100x100>" }
	after_post_process :save_image_dimensions

	validates :title, presence: true
	#validates :image, presence: true
	validates :time, presence: true
	validates :date, presence: true


  def save_image_dimensions
    geo = Paperclip::Geometry.from_file(image.queued_for_write[:original])
    self.image_width = geo.width
    self.image_height = geo.height
  end

end

app/models/timeline_object.rb
class TimelineObject < ActiveRecord::Base
	
	belongs_to :user

	attr_accessible :title, :user_id, :description, :image
	has_attached_file :image, :styles => {:medium => "400x400#", :thumb => "100x100#" }

	has_many :events 	

	validates :title, presence: true

  def get_events
    sorted_events = events.sort_by {|x| [x.date, x.time]}
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :timeline_objects

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, 
  :remember_me, :user_name

  validates :user_name, presence: true, uniqueness: true, format:{
														  	with: /^[a-zA-Z0-9_-]+$/,
														  	message: 'Must be formatted correctly.'
														  }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!
  # GET /events
  # GET /events.json
  # def index
  #   @events = Event.all.sort_by {|x| [x.date, x.time]}

  #   respond_to do |format|
  #     format.html # index.html.erb
  #     format.json { render json: @events }
  #   end
  # end 

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.create( params[:event] )
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
 end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/static_controller.rb
# static_controller.rb
class StaticController < ApplicationController
  def show
    render params[:page]
  end
end

app/controllers/timeline_objects_controller.rb
class TimelineObjectsController < ApplicationController
  before_filter :authenticate_user!

  # GET /timeline_objects
  # GET /timeline_objects.json
  def index
    @timeline_objects = TimelineObject.where(:user_id => current_user.id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @timeline_objects }
    end
  end

  # GET /timeline_objects/1
  # GET /timeline_objects/1.json
  def show
    @timeline_object = TimelineObject.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @timeline_object }
    end
  end

  # GET /timeline_objects/new
  # GET /timeline_objects/new.json
  def new
    @timeline_object = TimelineObject.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @timeline_object }
    end
  end

  # GET /timeline_objects/1/edit
  def edit
    @timeline_object = TimelineObject.find(params[:id])
  end

  # POST /timeline_objects
  # POST /timeline_objects.json
  def create
    @timeline_object = TimelineObject.new(params[:timeline_object])
    @timeline_object.user_id = current_user.id
    respond_to do |format|
      if @timeline_object.save
        format.html { redirect_to @timeline_object, notice: 'Timeline object was successfully created.' }
        format.json { render json: @timeline_object, status: :created, location: @timeline_object }
      else
        format.html { render action: "new" }
        format.json { render json: @timeline_object.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /timeline_objects/1
  # PUT /timeline_objects/1.json
  def update
    @timeline_object = TimelineObject.find(params[:id])

    respond_to do |format|
      if @timeline_object.update_attributes(params[:timeline_object])
        format.html { redirect_to @timeline_object, notice: 'Timeline object was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @timeline_object.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /timeline_objects/1
  # DELETE /timeline_objects/1.json
  def destroy
    @timeline_object = TimelineObject.find(params[:id])
    @timeline_object.destroy

    respond_to do |format|
      format.html { redirect_to timeline_objects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/timeline_objects_helper.rb
module TimelineObjectsHelper
end

app/views/events/_event_partial.html.erb
<div class="container-fluid modal hide fade" id="<%=event.id%>">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h2 class="modalheader"><%= event.title %> </h2>
  </div>

     <div class="span12 modaldetails">
        <div class="span4">
          <p>
            <%= image_tag event.image.url(:medium) %>
          </p>
        </div>
        <div class="span7">
          <p>
            <h3 class="with-blue">Date:</h3>
            <%= event.date %>
          </p>
          <p>
            <h3 class="with-blue">Time:</h3>
            <%= event.time %>
          </p>
          <p>
            <h3 class="with-blue">Description:</h3>
            <div class="description-field">
            <%= event.description %>
          </div>
          </p>
        </div>
      </div>
      <div class="span2 offset10">
          <%= link_to 'Edit', edit_event_path(event) %> |
          <%= link_to "Delete", event, method: :delete, data: { confirm: "Are you sure you want to delete this event?"} %> | 
          <%= link_to 'Back', timeline_object_path(event.timeline_object_id) %>
      </div>

</div>

app/views/events/_form.html.erb
<div class="span12 offset2">
  <%= simple_form_for(@event, html: {class: "form-horizontal"}) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="container-fluid">
  <h2 class="with-yellow">New Event</h2>
  <% timeline_id = params[:data] %>
    <div class="form-inputs">
      <%= f.input :title, :required => true, :autofocus => true %>
    </div>

  <div class="row-fluid">
    <div class="span7">
      <div class="field">
        <%= f.label :description %>
        <%= f.text_area :description, :style => "width:420px;", :required => true %>
      </div>
    </div>
    <div class="span5">
    </br>
      <div class="field">
        <%= f.label :image %>
        <%= f.file_field :image %>
      </div>
    </br>
      <div class="field">
        <%= f.label :date %>
        <%= f.text_field :date, :value=>Date.today.strftime('%m/%d/%Y'), :id =>"dp5" %>
      </div> 
    </br>
      <div class="field">
        <%= f.label :time%>
        <%= f.text_field :time, :value=>Time.current.strftime('%H:%M') %>
      </div>
      <div class="id hidden">
        <%= f.text_field :timeline_object_id, :value=> timeline_id %>
      </div>
      </br></br></br></br></br></br></br></br>
      <div class="actions">
        <%= f.button :submit, :class => "btn btn-large btn-block btn-custom" %>
    </div>
    </div>
  </div>
</div>


</div>

<% end %>

app/views/events/edit.html.erb
<div class="maincontainer pattern-background">
  <div class="offset">
    <div class="span12 offset2">

      <%= simple_form_for(@event, html: {class: "form-horizontal"}) do |f| %>
      <% if @event.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>
        <ul>
          <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
      <% end %>

      <div class="container-fluid">
        <h2 class="with-yellow"><%= @event.title %></h2>

        <div class="form-inputs">
          <%= f.input :title, :required => true, :autofocus => true %>
        </div>

        <div class="row-fluid">
          <div class="span7">
            <div class="field">
              <%= f.label :description %>
              <%= f.text_area :description, :style => "width:420px;", :required => true %>
            </div>
          </div>
          <div class="span5">
          </br>
          <div class="field">
            <%= f.label :image %>
            <%= f.file_field :image %>
          </div>
        </br>
        <div class="field">
          <%= f.label :date %>
          <%= f.text_field :date, :value=>Date.today.strftime('%m/%d/%Y'), :id =>"dp5" %>
        </div> 
      </br>
      <div class="field">
        <%= f.label :time%>
        <%= f.text_field :time, :value=>Time.current.strftime('%I%M%p'), :id =>"tp1" %>
      </div>
      <div class="id hidden">
        <%= f.text_field :timeline_object_id, :value=> @event.timeline_object_id %>
      </div>
    </br></br></br></br></br></br></br></br>
    <div class="actions">
      <%= f.button :submit, :class => "btn btn-large btn-block btn-custom" %>
    </div>
  </div>
</div>

<% end %>
</div>
</div>
</div>

app/views/events/new.html.erb
<div class="maincontainer pattern-background">
	<div class="offset">
		<%= render 'form' %>
	</div>
</div>

app/views/events/show.html.erb
<div class="maincontainer pattern-background">
  <div class="offset">
    <div class="container-fluid">
      <div class="span12 offset1">
      <h2 class="with-yellow"><%= @event.title %> </h2>
    </div>
      <div class="span12 showevent offset1">
        <div class="span4">
          <p>
            <%= image_tag @event.image.url(:medium) %>
          </p>
        </div>
        <div class="span7">
          <p>
            <h3 class="with-blue">Date:</h3>
            <%= @event.date %>
          </p>
          <p>
            <h3 class="with-blue">Time:</h3>
            <%= @event.time %>
          </p>
          <p>
            <h3 class="with-blue">Description:</h3>
            <%= @event.description %>
          </p>
        </div>
      </div>
      <div class="footer span2 offset12">
          <%= link_to 'Edit', edit_event_path(@event) %> |
          <%= link_to "Delete", @event, method: :delete, data: { confirm: "Are you sure you want to delete this event?"} %> | 
          <%= link_to 'Back', timeline_object_path(@event.timeline_object_id) %>
      </div>
    </div>
    </div>
</div>

app/views/home/index.html.erb
	<div id="homecontainer">
			<div class="message">
			<% if flash[:notice] %>
				<div class="alert alert-success">
					<button class="close" data-dismiss="alert">x</button>
					<%= flash[:notice] %>
				</div>
			<% end %>
			<% if flash[:alert] %>
				<div class="alert alert-error">
					<button class="close" data-dismiss="alert">x</button>
					<%= flash[:alert] %>
				</div>
			<% end %>
		</div>
		<div class="span12">
			<div class="homelinks span7 offset8">
				<div class="page-header span7">
					<div class="span7">
						<% if user_signed_in? %>
							<h1>Welcome, <%= current_user.user_name %></h1>
						<% else %>
							<h1>Welcome to Timeline.</h1>
						<% end %>
					</div>
				</div>
				<div class="span7">
					<% if user_signed_in? %>
					<div class="buttoncontainer span6">
						<%= link_to "New Timeline", newtimeline_path, class: "btn btn-custom btn-large btn-block" %>
						<%= link_to "Your Timelines", timelines_path, class: "btn btn-custom btn-large btn-block" %>
					<% else %>
					<div class="buttoncontainer span6">
						<%= link_to "Sign Up!", register_path, class: "btn btn-custom btn-large btn-block" %>
						<%= link_to "Log In", login_path, class: "btn btn-custom btn-large btn-block" %>
						<% end %>
					</div>
				</div>
			</div>
		</div>
	</div>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Timeline</title>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
</head>
<body>
	<script type="text/javascript">
	function Randomize() {
		var images = new Array("img1.jpg","img2.jpg","img3.jpg","img4.jpg");
		var imageNum = Math.floor(Math.random() * images.length);
		document.getElementById("homecontainer").style.backgroundImage = "url('/assets/" + images[imageNum] + "')";
	}
	window.onload = Randomize;
	</script>
	<style type="text/css">
	#homecontainer {
		display: block;
		background-image: url('img1.jpg');
		background-repeat:no-repeat;
		background-size:100% 100%;
		min-width: 50%;
		height: 100%;
		width: 100%;
	}
	</style>
	<div class="navbar navbar-fixed-top navbar-inverse">
		<div class="navbar-inner">
			<div class="container">
				<a href='<%= home_index_path %>' class="brand"> Timeline</a>
				<ul class="nav">
<!-- 					Add menu bar stuff here
-->				</ul>
<ul class="nav pull-right">
	<% if user_signed_in? %>
	<li><a href='<%= newtimeline_path %>'>New Timeline</a></li>

	<li><a href='<%= timelines_path %>'>Your Timelines</a></li>



	<li class="dropdown">
		<a href="#" class="dropdown-toggle" data-toggle="dropdown">
			Options
			<b class="caret"></b>
		</a>
		<ul class="dropdown-menu">
			<li><a href='<%= edit_user_registration_path %>'>Account</a></li>
			<li><%= link_to "Log Out", destroy_user_session_path, :method => :delete  %></li>
			<li><%= link_to "About", page_path("about.html") %></li>
		</ul>
	</li>

	<% else %>
	<li><%= link_to "Sign Up", register_path %></li>
	<li><%= link_to "Log In", login_path %></li>
	<li><%= link_to "About", page_path("about.html") %></li>
	<% end %>
</ul>
</div>
</div>
</div>

<div class="maincontainer">
	<% if flash[:notice] %>
	<div class="alert alert-success">
		<button class="close" data-dismiss="alert">x</button>
		<%= flash[:notice] %>
	</div>
	<% end %>
	<% if flash[:alert] %>
	<div class="alert alert-error">
		<button class="close" data-dismiss="alert">x</button>
		<%= flash[:alert] %>
	</div>
	<% end %>
	<%= yield %>
</div>


</body>
</html>

app/views/pages/about.html.erb
<div class="maincontainer pattern-background">
  <div class="offset">
    <div class="container-fluid">
      <div class="span12 offset2">
        <h2 class="with-yellow">About</h2>
      </div>
      <div class="entry offset2">
        <div class="wordwrap">
        <p class="yellow center"> Timeline is a simple website aimed at allowing users to upload pictures
          display them in a chronological manner.  </p>
        <p class="yellow"> Why? </p>
        <p class="blue"> Well, who wouldn't want to display pictures in order of time and date? Timeline can be used
          to display timed and dated media (right now only photos!) simply for viewing yourself, sharing with others,
          or education. </p>

        <p class="yellow"> How? </p>
        <p class="blue"> Right now it's pretty straight forward. Follow the prompts to create a new timeline and add media from your computer. Then you can enter the time, date, and any details. Oh, and you can edit and delete after creation!</p>
        <p class="yellow"> Who? </p>
         <p class="blue"> Right now, Timeline is the sole creation and Senior Project of Meredith Myers, undergraduate at American University.</br>
        You can check out the code at <a href="https://github.com/mmyers89/timeline" target="_blank">Github</a> </br>
        And, if you questions, comments or problems, you can email the developer directly at <a href="mailto:myers@myersmeredith.com " target="_blank">myers@myersmeredith.com</a></p>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/pages/terms.html.erb
<div class="maincontainer pattern-background">
  <div class="offset">
    <div class="container-fluid">
      <div class="span12 offset2">
        <h2 class="with-yellow">Terms & Conditions</h2>
      </div>
      <div class="entry wordwrap">
        <p class="yellow center"> It's simple. By clicking "Sign Up", you're agreeing to three things: </p>
      
        <p class="terms blue"><strong>1.</strong> <em> Don't upload images that aren't yours or you wouldn't want your mother to see. </em>   If you do,
        it isn't the fault of the website owners because... </p>
        <p class="terms blue"><strong>2.</strong> <em>The website owners do not own any of the content on this site,</em>   and in no way claim responsibility for content, external links, or inaccuracies added by users. </p>
        <p class="terms blue"><strong>3.</strong> <em>Finally,</em> if you upload something the website owners determine is under copyright or  deemed  inflammatory,
           the website owners reserve the right to remove the content. </p>
        
        <p class="terms blue center"><strong>That's it. For the time being, this website is only for educational purposes, and, if you oblige  the three statements above, it's yours to enjoy.</strong></p>
      </div>

    </div>
  </div>
</div>

app/views/timeline_objects/_form.html.erb
<div class="span12">
	<div class="entry-no-color offset2">
		<%= simple_form_for(@timeline_object) do |f| %>
			<% if @timeline_object.errors.any? %>
			<div id="error_explanation">
				<h2><%= pluralize(@timeline_object.errors.count, "error") %> prohibited this timeline from being saved:</h2>

				<ul>
					<% @timeline_object.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
			<% end %>

		<h2 class="with-yellow">New Timeline</h2>

		<div class="form-inputs">
			<%= f.input :title, :required => true, :autofocus => true %>
			<%= f.input :description %>
			<p> Image Thumbnail </br><%= f.file_field :image, :required => true %></p>
		</div>
		


		<div class="small-footer span12">
			<div class="container span4">
				<%= f.button :submit,"Make Timeline", :class => "btn btn-custom btn-large btn-block" %>
			</div>
		</div>
		<% end %>
	</div>
</div>

app/views/timeline_objects/edit.html.erb
<div class="maincontainer pattern-background">
	<div class="offset">
<div class="span12">
	<div class="entry offset2">
		<%= simple_form_for(@timeline_object) do |f| %>
			<% if @timeline_object.errors.any? %>
			<div id="error_explanation">
				<h2><%= pluralize(@timeline_object.errors.count, "error") %> prohibited this timeline from being saved:</h2>

				<ul>
					<% @timeline_object.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
			<% end %>

		<h2 class="with-yellow"><%= @timeline_object.title %></h2>

		<div class="form-inputs">
			<%= f.input :title, :required => true, :autofocus => true %>
			<%= f.input :description %>
			<p> Image Thumbnail </br><%= f.file_field :image, :required => true %></p>
		</div>
		


		<div class="small-footer span12">
			<div class="container span4">
				<%= f.button :submit,"Save Changes", :class => "btn btn-custom btn-large btn-block" %>
			</div>
		</div>
		<% end %>
	</div>
</div>


	</div>
</div>

app/views/timeline_objects/index.html.erb
<div class="maincontainer pattern-background">
	<div class="offset">
		<div class="span10 offset2 row-fluid">
			<div class="container-fluid">
			<h2>Your Timelines</h2>

			<% @timeline_objects.each do |timeline_object| %>
			<div class="indexitem span5 row-fluid">
				<blockquote>
					<p class="title"><%= timeline_object.title %></p>
					<p> <%= link_to (image_tag timeline_object.image.url(:thumb)), timeline_object %> </p>
					<small> <%= link_to 'Edit', edit_timeline_object_path(timeline_object) %> | <%= link_to 'Delete', timeline_object, method: :delete, data: { confirm: 'Are you sure?' } %> </td></small>
				</blockquote>
			</div>
			<% end %>
			<div class="footer span10">
				<div class="container span4 offset7">
					<%= link_to "New Timeline", new_timeline_object_path, class: "btn btn-custom btn-large btn-block" %>
				</div>
			</div>
		</div>
	</div>
	</div>
</div>

app/views/timeline_objects/new.html.erb
<div class="maincontainer pattern-background">
	<div class="offset">
		<%= render 'form' %>

	</div>
</div>

app/views/timeline_objects/show.html.erb
<!-- <link rel="stylesheet" href="../assets/style.css" /> -->

<div class="maincontainer pattern-background">
  <div class="offset">
<div class="timelineindexheader span12 offset2">
  <div class="timelinethumb span2">
    <%= image_tag @timeline_object.image.url(:thumb) %>
  </div>
  <div class="displaytimelinetitle span8">
    <p class="title">
      <%= @timeline_object.title %>
    </p>
    <p>
      <%= @timeline_object.description %>
    </p>
  </div>
</div>

<div class="isotopecontainer span12">
<% currentdate="none"%>
<div id="eventcontainer">
<!-- Go through each event (they are already ordered) and display -->
<% @timeline_object.get_events.each do |event| %>

  <%= render "events/event_partial", event: event %>


    <!-- Set up the popover with hidden modal. -->
    <div class="element other nonmetal large" data-symbol="Bi" data-category="post-transition">
      <p class="number"><%= event.title %></p>
      <div class = "symbol"><%= link_to(image_tag(event.image.url(:medium)), "##{event.id}", {:data => {:toggle => "modal"}}) %></div>
      <h2 class="name"><%= event.time %></h2>
      <p class="weight"><%= event.date %></p>

    </div>
<% end %>

</div>

  <script>
    $(function(){

      var $container = $('#eventcontainer');
      $container.imagesLoaded(function(){
        $container.isotope({
          layoutMode : 'spineAlign',
          spineAlign: {
              gutterWidth: 30
          },
          itemSelector : '.element',
  
      });
     });
      //   // add randomish size classes
      // $container.find('.element').each(function(){
      //   var $this = $(this),
      //       number = parseInt( $this.find('.number').text(), 10 );
      //   if ( number % 7 % 2 === 1 ) {
      //     $this.addClass('width2');
      //   }
      //   if ( number % 3 === 0 ) {
      //     $this.addClass('height2');
      //   }
      // });
    });
    // custom layout mode spineAlign
  $.Isotope.prototype._spineAlignReset = function() {
    this.spineAlign = {
      colA: 0,
      colB: 0
    };
  };

  $.Isotope.prototype._spineAlignLayout = function( $elems ) {
    var instance = this,
        props = this.spineAlign,
        gutterWidth = Math.round( this.options.spineAlign && this.options.spineAlign.gutterWidth ) || 0,
        centerX = Math.round(this.element.width() / 2);

    $elems.each(function(){
      var $this = $(this),
          isColA = props.colA <= props.colB,
          x = isColA ?
            centerX - ( $this.outerWidth(true) + gutterWidth / 2 ) : // left side
            centerX + gutterWidth / 2, // right side
          y = isColA ? props.colA : props.colB;
      instance._pushPosition( $this, x, y );
      props[( isColA ? 'colA' : 'colB' )] += $this.outerHeight(true);
    });
  };

  $.Isotope.prototype._spineAlignGetContainerSize = function() {
    var size = {};
    size.height = this.spineAlign[( this.spineAlign.colB > this.spineAlign.colA ? 'colB' : 'colA' )];
    return size;
  };

  $.Isotope.prototype._spineAlignResizeChanged = function() {
    return true;
  };
  </script>
</div>
<div class="eventnew span12">
    <div class="span5 offset9">
    <%= link_to "Add Event", new_event_path(:data => @timeline_object.id), class: "btn btn-custom btn-large btn-block" %>
    </div>
</div> 

</div>
</div>